# Generated by Django 2.2.7 on 2019-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'verbose_name': 'Revenue', 'verbose_name_plural': 'Revenues'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
    ]
