# Generated by Django 2.2.7 on 2020-01-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_revenue_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.FloatField(verbose_name='Value')),
                ('refund_date', models.DateField(verbose_name='Refund date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Insurance Final',
                'verbose_name_plural': 'Insurance Final',
            },
        ),
        migrations.CreateModel(
            name='InsurancePrimary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.FloatField(verbose_name='Value')),
                ('refunded', models.BooleanField(default=False, verbose_name='Refunded')),
                ('refunded_by', models.CharField(choices=[('cash', 'cash'), ('bank', 'bank')], max_length=100, verbose_name='Refunded by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Insurance Primary',
                'verbose_name_plural': 'Insurance Primary',
            },
        ),
    ]
