# Generated by Django 2.2.7 on 2020-01-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_insurancefinal_insuranceprimary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprimary',
            name='refunded_by',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('bank', 'bank')], max_length=100, null=True, verbose_name='Refunded by'),
        ),
    ]
