# Generated by Django 2.2.7 on 2019-12-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startbalance',
            options={'verbose_name': 'Start balance'},
        ),
    ]
