# Generated by Django 2.2.7 on 2019-12-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20191216_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startbalance',
            name='bank',
            field=models.FloatField(default=0, verbose_name='Bank balance'),
        ),
        migrations.AlterField(
            model_name='startbalance',
            name='cash',
            field=models.FloatField(default=0, verbose_name='Cash balance'),
        ),
    ]
