# Generated by Django 2.2.7 on 2019-11-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_info',
            field=models.TextField(blank=True, help_text='bank account number, E-wallet, ...etc', null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='payment_info',
            field=models.TextField(blank=True, help_text='bank account number, E-wallet, ...etc', null=True),
        ),
    ]
