# Generated by Django 2.2.7 on 2019-11-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20191123_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Current', 'Current'), ('Expected', 'Expected')], default='Current', max_length=50),
        ),
    ]
