# Generated by Django 2.2.7 on 2019-11-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPaymentCutValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.CustomerPaymentCut')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=100)),
                ('value', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='customers.Customer')),
                ('cuts', models.ManyToManyField(to='customers.CustomerPaymentCutValue')),
            ],
        ),
    ]
