# Generated by Django 2.2.7 on 2019-11-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20191130_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('New', 'New'), ('Current', 'Current'), ('Expected', 'Expected'), ('Facebook', 'Facebook')], default='Current', max_length=50),
        ),
    ]
