# Generated by Django 2.2.7 on 2019-12-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20191208_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customerpayment',
            options={'verbose_name': 'Customer payment', 'verbose_name_plural': 'Customer payments'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=254, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('New', 'New'), ('Current', 'Current'), ('Expected', 'Expected'), ('Facebook', 'Facebook')], default='Current', max_length=50, verbose_name='Customer type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateField(verbose_name='Join date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_info',
            field=models.TextField(blank=True, help_text='bank account number, E-wallet, ...etc', null=True, verbose_name='Payment info'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='person_job',
            field=models.CharField(default='-', max_length=200, verbose_name='Person job'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='person_name',
            field=models.CharField(default='-', max_length=200, verbose_name='Person name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='customers.Customer', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='cuts',
            field=models.FloatField(default=0, verbose_name='Cuts'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='fines',
            field=models.FloatField(default=0, verbose_name='Fines'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='perks',
            field=models.FloatField(default=0, verbose_name='Perks'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=254, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='join_date',
            field=models.DateField(verbose_name='Join date'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='payment_info',
            field=models.TextField(blank=True, help_text='bank account number, E-wallet, ...etc', null=True, verbose_name='Payment info'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
    ]
