# Generated by Django 2.2.7 on 2019-12-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20191216_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
