# Generated by Django 2.2.7 on 2019-12-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customerpayment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='customers.Customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=100, verbose_name='Payment method'),
        ),
    ]
