# Generated by Django 2.2.7 on 2019-12-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20191216_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=100, verbose_name='Payment method')),
                ('value', models.FloatField(verbose_name='Value')),
                ('cuts', models.FloatField(default=0, verbose_name='Cuts')),
                ('fines', models.FloatField(default=0, verbose_name='Fines')),
                ('perks', models.FloatField(default=0, verbose_name='Perks')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payments', to='customers.Seller', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Seller payment',
                'verbose_name_plural': 'Seller payments',
            },
        ),
    ]
