# Generated by Django 2.2.7 on 2019-12-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_sellerpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerpayment',
            name='customer',
        ),
        migrations.AddField(
            model_name='sellerpayment',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_payments', to='customers.Seller', verbose_name='Seller'),
        ),
    ]
