# Generated by Django 2.2.7 on 2019-12-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191228_2305'),
        ('customers', '0014_auto_20191221_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.CustomerOrder', verbose_name='Order'),
        ),
    ]
