# Generated by Django 2.2.7 on 2019-11-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191123_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Customer Order', 'verbose_name_plural': 'Customer Orders'},
        ),
    ]
