# Generated by Django 2.2.7 on 2019-12-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
