# Generated by Django 2.2.7 on 2019-12-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191216_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'verbose_name': 'Customer Order', 'verbose_name_plural': 'Customer Orders'},
        ),
        migrations.AlterModelOptions(
            name='sellerorder',
            options={'verbose_name': 'Seller Order', 'verbose_name_plural': 'Seller Orders'},
        ),
    ]
