# Generated by Django 2.2.7 on 2019-12-28 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_auto_20191216_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='cuts',
            field=models.FloatField(default=0, verbose_name='Cuts'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='fines',
            field=models.FloatField(default=0, verbose_name='Fines'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='perks',
            field=models.FloatField(default=0, verbose_name='Perks'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sales Representative'),
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='cuts',
            field=models.FloatField(default=0, verbose_name='Cuts'),
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='fines',
            field=models.FloatField(default=0, verbose_name='Fines'),
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='perks',
            field=models.FloatField(default=0, verbose_name='Perks'),
        ),
    ]
